### ISSUE TITLE
Project directories containing a hyphen don't work

### ISSUE THREAD

**Issue by saphieron** [es-ude/BazelCProjectCreator#11]
Created a project (mostly based on the autogenerated gitlab folder) with the name elastic-node-middleware. 

When running bazel sync for the first time i get the following error.

```
saphieron@saphX1LM:~/git/elastic-node-middleware$ bazel sync
Starting local Bazel server and connecting to it...
ERROR: /home/saphieron/git/elastic-node-middleware/WORKSPACE:1:1: elastic-node-middleware is not a legal workspace name
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': in /home/saphieron/git/elastic-node-middleware/github.bzl: Encountered error while reading extension file 'tools/build_defs/repo/http.bzl': no such package '@bazel_tools//tools/build_defs/repo': error loading package 'external': Could not load //external package
Loading: loading...
```

Renaming the WORKSPACE file lines to not contain hyphens, such as
```
workspace(
    name = "elasticnodemiddleware"
)
```
makes it work. 
If this is a design issue or bazel doesn't allow this, it should be pointed out in the README.

**Comment by glencoe** [comment]
Yeah Workspace names are not allowed to contain hyphens. Not sure about including it in the README, just want to avoid the README becomes an outdated copy of parts of the official bazel documentation. My proposals for solving that issue:

1. Mention that the provided project name has to be a valid bazel workspace name and link to the corresponding section of the bazel documentation.
2. When given an invalid name warn the user about it and don't create the project
3. When given an invalid name convert it to a valid one by e.g. elastic-node -> elastic_node

Of course combinations are possible, what do you think?

**Comment by saphieron** [comment]
If the script is only compatible with a given bazel version anyway I don't see that much of a problem, as we need to keep track of all changes anyway. 

My biggest concern, as usual is, that if we give this to new people/students, they won't read the bazel documentation. Let's face it, no student reads further than, if even, this readme. Especially with the trap of gitlab inserting hyphens when using spaces in the repo name, I just feel like we can avoid a lot of trouble when creating new projects by pointing exactly that part out in our readme. 

EDIT: Just reread the comment again. Only saying that the name's invalid is probably not going to help new students, unless the error message also points to some kind of official bazel docu describing exactly that. In which case we potentially have the same problem of that link potentially becoming stale/obsolete in the future. I guess in the end, i feel like we will need both...

**Comment by Saphieron** [comment]
Just reread the comment again. Only saying that the name's invalid is probably not going to help new students, unless the error message also points to some kind of official bazel docu describing exactly that. In which case we potentially have the same problem of that link potentially becoming stale/obsolete in the future. I guess in the end, i feel like we will need both...
