### ISSUE TITLE
src folder empty on creation, does not get pushed on initial git commit

### ISSUE THREAD

**Issue by saphieron** [es-ude/BazelCProjectCreator#12]
According to the README the soures should be organised in the following folders:

´´´Project/
  app/
  | setup/
  docs/
  Project/
  src/
  test/
´´´
However, after creating a project, the src folder, and afaik also the setup folder, are empty. 
When committing and pushing this directly, the empty folders do not get pushed into git. To keep the folder structure intact, in case these folders are not filled directly after creation I suggest we create an .emptyfile file in each of those.

**Comment by glencoe** [comment]
I don't really see the problem here, as soon as you have content for these folders you can still push them.

**Comment by saphieron** [comment]
Because it's easy to break the project when initially sharing it.
Had it now, that i created a project, pushed it as initial commit, without adding anything, and handed that repo to someone else. At that point, after cloning the project, it was already broken, due to bazel expecting those empty folders (or so i was told). That's why adding empty invisible files should be a "nice" initial solution, until someone for the first time adds an actual file in those folders.

**Comment by glencoe** [comment]
Makes sense.

**Comment by magshee** [comment]
Solved by creating an empty hidden file in the src folder as seen in 1bdbb2bff3d461b273dc9e37692b7e86c0380de1
