### ISSUE TITLE
Add support for elastic node middleware python scripts

### ISSUE THREAD

**Issue by DerDavidos** [es-ude/BazelCProjectCreator#14]
When creating a project for the elastic node middleware the files in the templates folder from the elastic node repository should be cloned.

**Comment by DerDavidos** [comment]
When executing with pipe input() throws EOF Error. Works with: python <(curl https://raw.githubusercontent.com/es-ude/BazelCProjectCreator/elasticNodeSupport/create_bazel_project.py) MyProject.

**Comment by magshee** [comment]
I would say that it looks good so far. 
You might wanna consider writing `(y/N)` in the input message, as the capital letter is known as the default option.

I'm not really sure, but i think that the function `input()` should also be called inside a try/except block.
